version: '3.8'

services:
  web:
    build: .
    command: 'uvicorn main:app'
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
    - .env